//--------------------------------------------------------------------
// This is a boilerplate ChucK program generated by chuginate,
//     to help you test your new chugin, ChuGin Developer!
//--------------------------------------------------------------------
// 1) try running this program after building your chugin
//    (the bulid process should yield a pl_synth.chug file)
//
// 2) you can manullay load the chugin when you run this program
//    `chuck --chugin:pl_synth.chug pl_synth-test.ck`
//
// 3) OR you can put the chugin into your chugins search path
//    NOTE: not recommended until you feel the chugin to be
//    reasonably stable, as chugins in your chugins search paths
//    will automatically load every time you run `chuck` or
//    start the VM in miniAudicle...
//
// Want to see more information? Add the --verbose:3 (-v3) flag:
//    `chuck --chugin:pl_synth.chug pl_synth-test.ck -v3`
//--------------------------------------------------------------------
@import "pl_synth"

"
[6014,[[[7,0,0,1,255,0,7,0,0,1,255,0,0,100,0,3636,254,2,1199,254,4,71],[1,1,1,1,1,1,1,1,1,1,0,0,0,0,1,1,1,1,1,1],[[126,126,0,0,126,0,0,0,0,0,0,0,0,0,0,0,126,126,0,0,126]]],[[6,0,0,0,255,2,6,0,18,0,255,2,0,100000,56363,100000,199,2,200,254,8,24],[0,0,2,2,3,4,2,2,3,5,2,2,3,4,2,2,3,5],[[],[132],[133,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128],[125],[120]]],[[7,0,0,0,87,2,8,0,0,0,16,3,8,0,22,2193,255,3,1162,51,10,182,2,190,0,1,10,96],[0,0,0,0,0,0,1,1,1,1,1,1,1,1],[[149,149,0,0,149,0,149,0,149,149,0,0,149,0,149]]],[[8,0,0,0,65,2,6,0,0,0,243,3,0,200,7505,20000,204,4,6180,81,4,198,0,0,0,0,6,131],[0,0,0,0,0,0,0,0,0,0,1,1,2,3,1,1,2,3],[[132,0,0,0,0,0,0,0,133,0,0,0,137],[132,0,0,0,0,0,0,0,133,0,0,0,130],[132,0,0,0,0,0,0,0,133,0,0,0,125,0,0,0,0,0,0,0,125]]]]]
" => string quake_json;

// instantiate a pl_synth
pl_synth synth => dac;
synth.load(quake_json);

second => now;

